fields:
  - name: name
    type: text
    label: Name
    placeholder: "z.B. Arbeit"
    max: 80
    required: true
    column: 1
    row: 1

  - name: description
    type: text
    label: Beschreibung
    placeholder: "z.B. dienstliche Ordner"
    max: 200
    column: 1
    row: 2
    colspan: 2

  - name: color
    type: color
    label: Farbe
    column: 1
    row: 3
